# Generated by Django 4.1.2 on 2022-10-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="Portfolio/images/")),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
