# Generated by Django 4.1.2 on 2022-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyect",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
